gradle.ext.androidxMediaModulePrefix = ''

def media3RootDir = file(".")
gradle.ext.androidxMediaSettingsDir = media3RootDir.getCanonicalPath()
rootProject.name = 'androidx.media3'
gradle.ext.rootProjectIsAndroidXMedia3 = true

def modulePrefix = ':'

include modulePrefix + 'lib-common'
project(modulePrefix + 'lib-common').projectDir = new File(media3RootDir, 'libraries/common')

include modulePrefix + 'lib-container'
project(modulePrefix + 'lib-container').projectDir = new File(media3RootDir, 'libraries/container')

include modulePrefix + 'lib-database'
project(modulePrefix + 'lib-database').projectDir = new File(media3RootDir, 'libraries/database')

include modulePrefix + 'lib-datasource'
project(modulePrefix + 'lib-datasource').projectDir = new File(media3RootDir, 'libraries/datasource')

include modulePrefix + 'lib-datasource-okhttp'
project(modulePrefix + 'lib-datasource-okhttp').projectDir = new File(media3RootDir, 'libraries/datasource_okhttp')

include modulePrefix + 'lib-datasource-rtmp'
project(modulePrefix + 'lib-datasource-rtmp').projectDir = new File(media3RootDir, 'libraries/datasource_rtmp')

include modulePrefix + 'lib-decoder'
project(modulePrefix + 'lib-decoder').projectDir = new File(media3RootDir, 'libraries/decoder')

include modulePrefix + 'lib-decoder-av3a'
project(modulePrefix + 'lib-decoder-av3a').projectDir = new File(media3RootDir, 'libraries/decoder_av3a')

include modulePrefix + 'lib-exoplayer'
project(modulePrefix + 'lib-exoplayer').projectDir = new File(media3RootDir, 'libraries/exoplayer')

include modulePrefix + 'lib-exoplayer-dash'
project(modulePrefix + 'lib-exoplayer-dash').projectDir = new File(media3RootDir, 'libraries/exoplayer_dash')

include modulePrefix + 'lib-exoplayer-hls'
project(modulePrefix + 'lib-exoplayer-hls').projectDir = new File(media3RootDir, 'libraries/exoplayer_hls')

include modulePrefix + 'lib-exoplayer-rtsp'
project(modulePrefix + 'lib-exoplayer-rtsp').projectDir = new File(media3RootDir, 'libraries/exoplayer_rtsp')

include modulePrefix + 'lib-exoplayer-smoothstreaming'
project(modulePrefix + 'lib-exoplayer-smoothstreaming').projectDir = new File(media3RootDir, 'libraries/exoplayer_smoothstreaming')

include modulePrefix + 'lib-extractor'
project(modulePrefix + 'lib-extractor').projectDir = new File(media3RootDir, 'libraries/extractor')

include modulePrefix + 'lib-session'
project(modulePrefix + 'lib-session').projectDir = new File(media3RootDir, 'libraries/session')

include modulePrefix + 'lib-ui'
project(modulePrefix + 'lib-ui').projectDir = new File(media3RootDir, 'libraries/ui')

include modulePrefix + 'lib-ui-danmaku'
project(modulePrefix + 'lib-ui-danmaku').projectDir = new File(media3RootDir, 'libraries/ui_danmaku')

def media3StubDir = new File(media3RootDir.getParentFile(), '.github/media3-stubs')

include modulePrefix + 'test-utils'
project(modulePrefix + 'test-utils').projectDir = new File(media3StubDir, 'test-utils')

include modulePrefix + 'test-utils-robolectric'
project(modulePrefix + 'test-utils-robolectric').projectDir = new File(media3StubDir, 'test-utils-robolectric')

include modulePrefix + 'lib-inspector'
project(modulePrefix + 'lib-inspector').projectDir = new File(media3StubDir, 'lib-inspector')

include modulePrefix + 'test-data'
project(modulePrefix + 'test-data').projectDir = new File(media3StubDir, 'test-data')
